linkstack:
  enabled: true
  global:
    fullnameOverride: linkstack
  controllers:
    linkstack:
      type: deployment
      strategy: Recreate
      containers:
        linkstack:
          image:
            repository: ghcr.io/linkstackorg/linkstack
            tag: v4.8.5
            pullPolicy: IfNotPresent
          env:
            hostname: linkstack.lauckserv.net
            HTTP_SERVER_NAME: linkstack.lauckserv.net
            HTTPS_SERVER_NAME: linkstack.lauckserv.net
            SERVER_ADMIN: justin@lauckserv.com
            TZ: America/New_York
